import { z } from "zod";
const text = z.string().nullable();
const number = z.number().nullable();
const boolean = z.boolean().nullable();
export const vehicleSchema = z.object({
  licensePlate: z.string(),
  make: z.string(),
  model: text,
  vehicleType: text,
  bodyType: text,
  firstRegistrationDate: text,
  firstRegistrationNetherlandsDate: text,
  apkExpiryDate: text,
  fuelTypes: z.array(z.string()),
  powerKw: number,
  powerHp: number,
  electricPowerKw: number,
  massKg: number,
  readyMassKg: number,
  maxMassKg: number,
  payloadKg: number,
  catalogPrice: number,
  bpm: number,
  colorPrimary: text,
  colorSecondary: text.default(null),
  registrationDate: text.default(null),
  wamInsured: boolean.default(null),
  typeCode: text.default(null),
  variant: text.default(null),
  version: text.default(null),
  typeApprovalNumber: text.default(null),
  europeanCategory: text.default(null),
  bodyCode: text.default(null),
  numberOfWheels: number.default(null),
  standingPlaces: number.default(null),
  technicalMaxMassKg: number.default(null),
  combinationMaxMassKg: number.default(null),
  couplingMaxLoadKg: number.default(null),
  odometerJudgment: text.default(null),
  odometerJudgmentCode: text.default(null),
  odometerExplanation: text.default(null),
  odometerLastYear: number.default(null),
  recalls: z
    .array(
      z.object({
        reference: z.string(),
        statusCode: text,
        status: text,
        publicationDate: text,
        producer: text,
        producerReference: text,
        defect: text,
        consequences: text,
        remedy: text,
        risks: z.array(z.string()),
        url: text,
        phone: text,
      }),
    )
    .default([]),
  recallDetailsAvailable: z.boolean().default(false),
  axes: z
    .array(
      z.object({ number, position: text, trackCm: number, maxMassKg: number }),
    )
    .default([]),
  typeApproval: z
    .object({
      matched: z.boolean().default(false),
      transmissionCode: text.default(null),
      transmission: text.default(null),
      gears: number.default(null),
      lengthMm: number.default(null),
      widthMm: number.default(null),
      heightMm: number.default(null),
      wheelbaseMm: number.default(null),
    })
    .prefault({}),
  consumptionWltp: number.default(null),
  consumptionCity: number.default(null),
  consumptionHighway: number.default(null),
  emissionsCo2Wltp: number.default(null),
  emissionsCo2Nedc: number.default(null),
  particulateEmissionsWltp: number.default(null),
  particulateEmissions: number.default(null),
  noiseStationaryDb: number.default(null),
  noiseDrivingDb: number.default(null),
  noiseRpm: number.default(null),
  environmentalApproval: text.default(null),
  electricRangeKm: number.default(null),
  hybridClass: text.default(null),
  consumptionWeightedWltp: number.default(null),
  emissionsCo2WeightedWltp: number.default(null),
  numberOfSeats: number,
  numberOfDoors: number,
  engineCapacityCc: number,
  cylinders: number,
  emissionsCo2: number,
  emissionClass: text,
  consumptionCombined: number,
  electricConsumption: number,
  lengthCm: number,
  widthCm: number,
  heightCm: number,
  wheelbaseCm: number,
  towingBrakedKg: number,
  towingUnbrakedKg: number,
  maxSpeedKmh: number,
  isImport: boolean,
  isExported: boolean,
  isTaxi: boolean,
  recallPending: boolean,
  registrationPossible: boolean,
  source: z.object({
    name: z.string(),
    datasets: z.array(z.string()),
    fetchedAt: z.string(),
    missingFields: z.array(z.string()),
    derivedFields: z.array(z.string()),
    warnings: z.array(z.string()),
    schemaVersion: z.number().default(1),
  }),
});
export type Vehicle = z.infer<typeof vehicleSchema>;
